# Generated by Django 4.2.30 on 2026-07-17 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scanner_api", "0005_asset_assetvendor_client_device_fingerprint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("asset", "Asset Management"),
                            ("monitoring", "Monitoring"),
                            ("maintenance", "Maintenance"),
                            ("license", "License Management"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "source_object_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "source_object_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("information", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("emergency", "Emergency"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("monitoring", "Monitoring"),
                            ("maintenance", "Maintenance"),
                            ("license", "License"),
                            ("security", "Security"),
                            ("compliance", "Compliance"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "assigned_user",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("generated_time", models.DateTimeField(auto_now_add=True)),
                ("resolved_time", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, default="")),
                (
                    "escalation_level",
                    models.IntegerField(
                        default=0,
                        help_text="0=normal, 1=warning escalated, 2=critical escalated, 3=emergency escalated",
                    ),
                ),
                (
                    "dedup_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA256 hash for deduplication",
                        max_length=64,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "intelligence_alerts",
                "ordering": ["-generated_time"],
            },
        ),
        migrations.CreateModel(
            name="DashboardAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_alerts", models.IntegerField(default=0)),
                ("open_alerts", models.IntegerField(default=0)),
                ("critical_alerts", models.IntegerField(default=0)),
                ("notifications_today", models.IntegerField(default=0)),
                ("reports_generated", models.IntegerField(default=0)),
                ("security_violations", models.IntegerField(default=0)),
                ("audit_events_today", models.IntegerField(default=0)),
                ("compliance_violations", models.IntegerField(default=0)),
                ("pending_notifications", models.IntegerField(default=0)),
                ("snapshot_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "intelligence_dashboard_analytics",
                "ordering": ["-snapshot_time"],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("alerts", "Alerts"),
                            ("notifications", "Notifications"),
                            ("reports", "Reports"),
                            ("audit_logs", "Audit Logs"),
                            ("compliance_logs", "Compliance Logs"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "retention_period",
                    models.CharField(
                        choices=[
                            ("1_year", "1 Year"),
                            ("3_years", "3 Years"),
                            ("permanent", "Permanent"),
                        ],
                        default="1_year",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Retention Policy",
                "verbose_name_plural": "Retention Policies",
                "db_table": "intelligence_retention_policies",
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("asset_inventory", "Asset Inventory Report"),
                            ("asset_assignment", "Asset Assignment Report"),
                            ("asset_lifecycle", "Asset Lifecycle Report"),
                            ("asset_utilization", "Asset Utilization Report"),
                            ("online_devices", "Online Devices Report"),
                            ("device_health", "Device Health Report"),
                            ("hardware_change", "Hardware Change Report"),
                            ("software_inventory", "Software Inventory Report"),
                            ("upcoming_maintenance", "Upcoming Maintenance"),
                            ("maintenance_cost", "Maintenance Cost Report"),
                            ("downtime_analysis", "Downtime Analysis"),
                            ("vendor_performance", " Vendor Performance"),
                            ("expiring_licenses", "Expiring Licenses"),
                            ("compliance_report", "Compliance Reports"),
                            ("seat_utilization", "Seat Utilization Reports"),
                            ("cost_analysis", "Cost Analysis Reports"),
                            ("unauthorized_software", "Unauthorized Software"),
                            ("security_violations", "Security Violations"),
                            ("device_risk", "Device Risk Reports"),
                            ("audit_report", "Audit Reports"),
                            ("monthly_summary", "Monthly Summary"),
                            ("department_performance", "Department Performance"),
                            ("top_problematic_assets", "Top Problematic Assets"),
                            ("cost_overview", "Cost Overview"),
                            ("compliance_summary", "Compliance Summary"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="csv",
                        max_length=8,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "recipients",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated email addresses",
                    ),
                ),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "retention_policy",
                    models.CharField(
                        choices=[
                            ("1_year", "1 Year"),
                            ("3_years", "3 Years"),
                            ("permanent", "Permanent"),
                        ],
                        default="1_year",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "intelligence_scheduled_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["frequency", "is_active"],
                        name="intelligenc_frequen_8c02e5_idx",
                    ),
                    models.Index(
                        fields=["-next_run"], name="intelligenc_next_ru_d1b578_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("asset_inventory", "Asset Inventory Report"),
                            ("asset_assignment", "Asset Assignment Report"),
                            ("asset_lifecycle", "Asset Lifecycle Report"),
                            ("asset_utilization", "Asset Utilization Report"),
                            ("online_devices", "Online Devices Report"),
                            ("device_health", "Device Health Report"),
                            ("hardware_change", "Hardware Change Report"),
                            ("software_inventory", "Software Inventory Report"),
                            ("upcoming_maintenance", "Upcoming Maintenance"),
                            ("maintenance_cost", "Maintenance Cost Report"),
                            ("downtime_analysis", "Downtime Analysis"),
                            ("vendor_performance", " Vendor Performance"),
                            ("expiring_licenses", "Expiring Licenses"),
                            ("compliance_report", "Compliance Reports"),
                            ("seat_utilization", "Seat Utilization Reports"),
                            ("cost_analysis", "Cost Analysis Reports"),
                            ("unauthorized_software", "Unauthorized Software"),
                            ("security_violations", "Security Violations"),
                            ("device_risk", "Device Risk Reports"),
                            ("audit_report", "Audit Reports"),
                            ("monthly_summary", "Monthly Summary"),
                            ("department_performance", "Department Performance"),
                            ("top_problematic_assets", "Top Problematic Assets"),
                            ("cost_overview", "Cost Overview"),
                            ("compliance_summary", "Compliance Summary"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="csv",
                        max_length=8,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, help_text="JSON filter criteria"
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "file_data",
                    models.TextField(
                        blank=True, default="", help_text="Base64 encoded file data"
                    ),
                ),
                ("file_size", models.IntegerField(default=0)),
                ("row_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "intelligence_reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "-generated_at"],
                        name="intelligenc_report__5483ad_idx",
                    ),
                    models.Index(
                        fields=["status"], name="intelligenc_status_c7eb32_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("severity_information", models.BooleanField(default=True)),
                ("severity_warning", models.BooleanField(default=True)),
                ("severity_critical", models.BooleanField(default=True)),
                ("severity_emergency", models.BooleanField(default=True)),
                ("module_asset", models.BooleanField(default=True)),
                ("module_monitoring", models.BooleanField(default=True)),
                ("module_maintenance", models.BooleanField(default=True)),
                ("module_license", models.BooleanField(default=True)),
                ("module_security", models.BooleanField(default=True)),
                ("module_compliance", models.BooleanField(default=True)),
                ("module_system", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                            ("never", "Never"),
                        ],
                        default="instant",
                        max_length=16,
                    ),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "intelligence_notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("information", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("emergency", "Emergency"),
                        ],
                        default="information",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="unread",
                        max_length=16,
                    ),
                ),
                ("module", models.CharField(blank=True, default="", max_length=64)),
                (
                    "source_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("read_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="intelligence.alert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_notifications",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("iso_27001", "ISO 27001"),
                            ("itil", "ITIL"),
                            ("soc2", "SOC 2"),
                            ("internal", "Internal Security Policy"),
                            ("gdpr", "GDPR"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("control_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "control_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("partial", "Partially Compliant"),
                            ("not_applicable", "Not Applicable"),
                            ("not_audited", "Not Audited"),
                        ],
                        default="compliant",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("finding_details", models.JSONField(blank=True, default=dict)),
                (
                    "audited_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("audited_at", models.DateTimeField(auto_now_add=True)),
                ("next_audit_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_logs",
                        to="scanner_api.asset",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_compliance_logs",
                "ordering": ["-audited_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "browser_info",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "device_info",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("asset", "Asset Management"),
                            ("monitoring", "Monitoring"),
                            ("maintenance", "Maintenance"),
                            ("license", "License Management"),
                            ("settings", "Settings"),
                            ("admin", "Admin"),
                            ("intelligence", "Intelligence"),
                            ("organization", "Organization"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Failed Login"),
                            ("asset_created", "Asset Creation"),
                            ("asset_updated", "Asset Update"),
                            ("asset_assigned", "Asset Assignment"),
                            ("asset_deleted", "Asset Deletion"),
                            ("maintenance_changed", "Maintenance Changes"),
                            ("license_changed", "License Changes"),
                            ("user_created", "User Management"),
                            ("alert_resolved", "Alert Resolution"),
                            ("settings_changed", "Settings Changes"),
                            ("report_downloaded", "Report Downloads"),
                            ("report_generated", "Report Generated"),
                            ("employee_created", "Employee Created"),
                            ("employee_updated", "Employee Updated"),
                            ("department_changed", "Department Changed"),
                            ("location_changed", "Location Changed"),
                            ("data_exported", "Data Exported"),
                            ("data_imported", "Data Imported"),
                            ("system_action", "System Action"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("old_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "intelligence_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="intelligenc_timesta_4aa879_idx"
                    ),
                    models.Index(
                        fields=["module", "-timestamp"],
                        name="intelligenc_module_194c10_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="intelligenc_action_221008_idx",
                    ),
                    models.Index(
                        fields=["user_id", "-timestamp"],
                        name="intelligenc_user_id_74618c_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="intelligenc_severit_88b60a_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="intelligenc_ip_addr_a0caea_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("asset", "Asset Management"),
                            ("monitoring", "Monitoring"),
                            ("maintenance", "Maintenance"),
                            ("license", "License Management"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("monitoring", "Monitoring"),
                            ("maintenance", "Maintenance"),
                            ("license", "License"),
                            ("security", "Security"),
                            ("compliance", "Compliance"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("information", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("emergency", "Emergency"),
                        ],
                        default="warning",
                        max_length=16,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        help_text="e.g., threshold_gt, threshold_lt, equals, contains",
                        max_length=64,
                    ),
                ),
                (
                    "condition_field",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "condition_value",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("suppress_duplicates", models.BooleanField(default=True)),
                ("suppress_window_minutes", models.IntegerField(default=60)),
                (
                    "auto_resolve_minutes",
                    models.IntegerField(default=0, help_text="0 = no auto-resolve"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "intelligence_alert_rules",
                "ordering": ["module", "name"],
                "indexes": [
                    models.Index(
                        fields=["module", "is_active"],
                        name="intelligenc_module_30726c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=32)),
                (
                    "previous_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("new_status", models.CharField(blank=True, default="", max_length=16)),
                (
                    "previous_severity",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "new_severity",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "performed_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="intelligence.alert",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_alert_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["severity", "status"], name="intelligenc_severit_6a866f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["category", "status"], name="intelligenc_categor_e83d0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["module", "status"], name="intelligenc_module_be6bd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["-generated_time"], name="intelligenc_generat_79a650_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["dedup_hash"], name="intelligenc_dedup_h_610f6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["assigned_user"], name="intelligenc_assigne_e93bb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status", "-created_time"],
                name="intelligenc_user_id_34c5ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["severity", "status"], name="intelligenc_severit_67bd3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancelog",
            index=models.Index(
                fields=["framework", "status"], name="intelligenc_framewo_b6f888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancelog",
            index=models.Index(
                fields=["-audited_at"], name="intelligenc_audited_b1f9b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancelog",
            index=models.Index(
                fields=["severity"], name="intelligenc_severit_4a3787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerthistory",
            index=models.Index(
                fields=["alert", "-timestamp"], name="intelligenc_alert_i_40ee4f_idx"
            ),
        ),
    ]
