# Generated by Django 5.2.7 on 2026-05-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("hostname", models.CharField(default="", max_length=255)),
                ("platform", models.CharField(default="", max_length=128)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated tags",
                        max_length=512,
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "vendor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "vendor_contact",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("scan_interval", models.IntegerField(default=3600)),
                ("scan_enabled", models.BooleanField(default=True)),
                ("scan_requested", models.BooleanField(default=False)),
                (
                    "client_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "os_version",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("cpu_model", models.CharField(blank=True, default="", max_length=256)),
                ("ram_info", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "clients",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="ClientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "client_groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField(blank=True)),
            ],
            options={
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="AddonDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=128)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "addon_devices",
                "ordering": ["-added_at"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="scanner_api.clientgroup",
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("register", "Client Registered"),
                            ("approve", "Client Approved"),
                            ("scan", "Scan Completed"),
                            ("scan_request", "Scan Requested"),
                            ("delete", "Client Deleted"),
                            ("update", "Client Updated"),
                            ("login", "Admin Login"),
                            ("setting_change", "Setting Changed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="activity_lo_created_d8c226_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_type", models.CharField(default="scheduled", max_length=32)),
                ("scan_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "scan_results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "-created_at"],
                        name="scan_result_client__597143_idx",
                    )
                ],
            },
        ),
    ]
