# Generated by Django 4.2.30 on 2026-07-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="last_ip",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
