# Generated by Django 4.2.30 on 2026-07-13 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scanner_api", "0002_client_deleted_client_last_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "login_attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=255)),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("browser", models.CharField(blank=True, default="", max_length=128)),
                ("os", models.CharField(blank=True, default="", max_length=128)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("trusted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_fingerprints",
            },
        ),
        migrations.CreateModel(
            name="AdministratorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "profile_picture_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=20)),
                (
                    "dashboard_default",
                    models.CharField(default="dashboard", max_length=50),
                ),
                ("notification_email", models.BooleanField(default=True)),
                ("notification_in_app", models.BooleanField(default=True)),
                ("notification_daily_summary", models.BooleanField(default=False)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_enabled", models.BooleanField(default=False)),
                (
                    "mfa_secret",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "administrator_profiles",
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("browser", models.CharField(blank=True, default="", max_length=128)),
                ("os", models.CharField(blank=True, default="", max_length=128)),
                (
                    "device_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("session_duration", models.DurationField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "login_history",
                "ordering": ["-login_time"],
                "indexes": [
                    models.Index(
                        fields=["-login_time"], name="login_histo_login_t_365f72_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failure", "Login Failure"),
                            ("logout", "Logout"),
                            ("password_changed", "Password Changed"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("profile_updated", "Profile Updated"),
                            ("settings_updated", "Settings Updated"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("session_created", "Session Created"),
                            ("session_expired", "Session Expired"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("details", models.TextField(blank=True, default="")),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_logs_created_43fcd6_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="audit_logs_event_t_3207df_idx"
                    ),
                ],
            },
        ),
    ]
