# Generated by Django 4.2.30 on 2026-07-13 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "scanner_api",
            "0003_loginattempt_devicefingerprint_administratorprofile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "department_head",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                            ("Archived", "Archived"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_code", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("designation", models.CharField(max_length=255)),
                (
                    "manager_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Resigned", "Resigned"),
                            ("On Leave", "On Leave"),
                            ("Terminated", "Terminated"),
                            ("Retired", "Retired"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "profile_image",
                    models.TextField(
                        blank=True, default="", help_text="Base64 encoded image"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="scanner_api.department",
                    ),
                ),
            ],
            options={
                "db_table": "employees",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="OrgAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("department", "Department"),
                            ("location", "Location"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(max_length=255)),
                ("entity_name", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deactivated", "Deactivated"),
                            ("archived", "Archived"),
                            ("disabled", "Disabled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("previous_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                ("performed_by", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "org_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="org_audit_l_entity__23b147_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="org_audit_l_created_ad1b0d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("office_name", models.CharField(max_length=255)),
                (
                    "building_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("floor", models.CharField(blank=True, default="", max_length=50)),
                (
                    "room_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(blank=True, default="", max_length=128)),
                ("country", models.CharField(default="USA", max_length=128)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "office_manager",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Archived", "Archived"),
                            ("Closed", "Closed"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations",
                "ordering": ["office_name"],
                "unique_together": {("office_name", "city")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeAssetAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_assignments",
                        to="scanner_api.client",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_assignments",
                        to="scanner_api.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_asset_assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="scanner_api.location",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="scanner_api.employee",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="scanner_api.location",
            ),
        ),
    ]
