# Generated by Django 4.2.30 on 2026-07-16 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0004_department_employee_orgauditlog_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, unique=True
                    ),
                ),
                ("asset_name", models.CharField(max_length=255)),
                (
                    "asset_tag",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "qr_code",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "barcode",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("specifications", models.JSONField(blank=True, default=dict)),
                (
                    "image",
                    models.TextField(
                        blank=True, default="", help_text="Base64 encoded image"
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "residual_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "depreciation_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "purchase_order_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("warranty_start", models.DateField(blank=True, null=True)),
                ("warranty_end", models.DateField(blank=True, null=True)),
                (
                    "warranty_provider",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("amc_details", models.TextField(blank=True, default="")),
                (
                    "asset_status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Pending Approval", "Pending Approval"),
                            ("Approved", "Approved"),
                            ("Purchased", "Purchased"),
                            ("Available", "Available"),
                            ("Assigned", "Assigned"),
                            ("Maintenance", "Maintenance"),
                            ("Returned", "Returned"),
                            ("Lost", "Lost"),
                            ("Damaged", "Damaged"),
                            ("Retired", "Retired"),
                            ("Disposed", "Disposed"),
                            ("Archived", "Archived"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=24,
                    ),
                ),
                ("is_insured", models.BooleanField(default=False)),
                (
                    "insurance_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_audit_date", models.DateField(blank=True, null=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated tags",
                        max_length=512,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetVendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("address", models.TextField(blank=True, default="")),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "asset_vendors",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="device_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Hardware-based unique device identifier that survives IP changes",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="AssetTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transfer_date", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "transferred_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="scanner_api.asset",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_transfers_from",
                        to="scanner_api.department",
                    ),
                ),
                (
                    "from_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_transfers_from",
                        to="scanner_api.employee",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_transfers_from",
                        to="scanner_api.location",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_transfers_to",
                        to="scanner_api.department",
                    ),
                ),
                (
                    "to_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_transfers_to",
                        to="scanner_api.employee",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_transfers_to",
                        to="scanner_api.location",
                    ),
                ),
            ],
            options={
                "db_table": "asset_transfers",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="AssetDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_data", models.TextField(help_text="Base64 encoded file data")),
                ("file_type", models.CharField(blank=True, default="", max_length=64)),
                ("file_size", models.IntegerField(default=0)),
                (
                    "uploaded_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="scanner_api.asset",
                    ),
                ),
            ],
            options={
                "db_table": "asset_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bootstrap icon class",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="scanner_api.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "asset categories",
                "db_table": "asset_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("assignment_notes", models.TextField(blank=True, default="")),
                ("return_notes", models.TextField(blank=True, default="")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="scanner_api.asset",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments_v2",
                        to="scanner_api.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_assignments_v2",
                        to="scanner_api.employee",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments_v2",
                        to="scanner_api.location",
                    ),
                ),
            ],
            options={
                "db_table": "asset_assignments_v2",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="scanner_api.assetcategory",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_assets",
                to="scanner_api.client",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="scanner_api.department",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="scanner_api.location",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="scanner_api.asset",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="scanner_api.assetvendor",
            ),
        ),
        migrations.CreateModel(
            name="AssetHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Asset Created"),
                            ("updated", "Asset Updated"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Asset Assigned"),
                            ("returned", "Asset Returned"),
                            ("transferred", "Asset Transferred"),
                            ("maintenance_started", "Maintenance Started"),
                            ("maintenance_completed", "Maintenance Completed"),
                            ("retired", "Asset Retired"),
                            ("disposed", "Asset Disposed"),
                            ("document_added", "Document Added"),
                            ("hierarchy_changed", "Hierarchy Changed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("previous_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="scanner_api.asset",
                    ),
                ),
            ],
            options={
                "db_table": "asset_history",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["asset", "-timestamp"],
                        name="asset_histo_asset_i_6277f2_idx",
                    ),
                    models.Index(
                        fields=["action"], name="asset_histo_action_a3f451_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["asset_status"], name="assets_asset_s_472a10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["category"], name="assets_categor_840335_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["department"], name="assets_departm_1f9439_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["location"], name="assets_locatio_bd5830_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["-created_at"], name="assets_created_d09603_idx"
            ),
        ),
    ]
