# Generated by Django 4.2.30 on 2026-07-18 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scanner_api", "0005_asset_assetvendor_client_device_fingerprint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("key_hash", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rate_limit",
                    models.IntegerField(default=60, help_text="Requests per minute"),
                ),
                (
                    "allowed_ips",
                    models.TextField(
                        blank=True, default="", help_text="Comma-separated IPs"
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
