# Generated by Django 5.2.16 on 2026-07-22 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0007_company_alter_assetcategory_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assets",
                to="scanner_api.employee",
            ),
        ),
    ]
