# Generated by Django 5.2.16 on 2026-07-27 05:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0009_client_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="administratorprofile",
            unique_together={("company", "user")},
        ),
    ]
