# Generated by Django 5.2.16 on 2026-07-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0010_alter_administratorprofile_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=128, unique=True),
        ),
    ]
