# Generated by Django 5.2.16 on 2026-08-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0002_fix_company_fks"),
        ("scanner_api", "0011_company_slug_nullable"),
    ]

    operations = []