# Generated by Django 5.2.16 on 2026-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0012_merge_20260804"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="auto_approved",
            field=models.BooleanField(
                default=False,
                help_text="Approved automatically at registration; demoted to pending if auto-approve is turned off",
            ),
        ),
    ]
