# Generated by Django 4.2.30 on 2026-07-17 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scanner_api", "0005_asset_assetvendor_client_device_fingerprint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarrantyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "warranty_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, unique=True
                    ),
                ),
                ("warranty_start", models.DateField()),
                ("warranty_end", models.DateField()),
                ("warranty_provider", models.CharField(max_length=255)),
                (
                    "contract_number",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("amc_details", models.TextField(blank=True, default="")),
                (
                    "support_contact_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "support_contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "support_contact_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("Full", "Full Coverage"),
                            ("Parts", "Parts Only"),
                            ("Labor", "Labor Only"),
                            ("Limited", "Limited Warranty"),
                        ],
                        default="Full",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expiring Soon", "Expiring Soon"),
                            ("Expired", "Expired"),
                            ("Claimed", "Claimed"),
                            ("Archived", "Archived"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_records",
                        to="scanner_api.asset",
                    ),
                ),
            ],
            options={
                "db_table": "warranty_records",
                "ordering": ["warranty_end"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "license_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, unique=True
                    ),
                ),
                ("software_name", models.CharField(db_index=True, max_length=255)),
                ("vendor", models.CharField(blank=True, default="", max_length=255)),
                (
                    "product_edition",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("version", models.CharField(blank=True, default="", max_length=128)),
                (
                    "license_key_encrypted",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Encrypted full license key",
                        max_length=512,
                    ),
                ),
                (
                    "license_key_masked",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Masked display of license key",
                        max_length=128,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("Per User", "Per User"),
                            ("Per Device", "Per Device"),
                            ("Subscription", "Subscription"),
                            ("OEM", "OEM"),
                            ("Enterprise", "Enterprise"),
                            ("Volume", "Volume"),
                            ("Trial", "Trial"),
                            ("Open Source", "Open Source"),
                        ],
                        default="Per User",
                        max_length=20,
                    ),
                ),
                ("purchased_seats", models.IntegerField(default=1)),
                ("seats_used", models.IntegerField(default=0)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Active", "Active"),
                            ("Expiring Soon", "Expiring Soon"),
                            ("Expired", "Expired"),
                            ("Suspended", "Suspended"),
                            ("Archived", "Archived"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses",
                        to="scanner_api.department",
                    ),
                ),
            ],
            options={
                "db_table": "software_licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "maintenance_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, unique=True
                    ),
                ),
                (
                    "asset_category_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("Preventive", "Preventive"),
                            ("Corrective", "Corrective"),
                            ("Emergency", "Emergency"),
                            ("Inspection", "Inspection"),
                            ("Upgrade", "Upgrade"),
                            ("Repair", "Repair"),
                            ("Replacement", "Replacement"),
                            ("Calibration", "Calibration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Pending Approval", "Pending Approval"),
                            ("Approved", "Approved"),
                            ("Scheduled", "Scheduled"),
                            ("In Progress", "In Progress"),
                            ("Waiting Parts", "Waiting Parts"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("Overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=24,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "vendor_contact",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "technician",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Deadline for completion", null=True
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        default="Medium",
                        max_length=16,
                    ),
                ),
                ("recurring", models.BooleanField(default=False)),
                (
                    "recurrence_interval_days",
                    models.IntegerField(default=0, help_text="0 = not recurring"),
                ),
                ("next_occurrence", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="scanner_api.asset",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_records",
                        to="scanner_api.department",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("previous_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "maintenance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="maintenance.maintenancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_data", models.TextField(help_text="Base64 encoded file data")),
                ("file_type", models.CharField(blank=True, default="", max_length=64)),
                ("file_size", models.IntegerField(default=0)),
                (
                    "uploaded_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "maintenance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="maintenance.maintenancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maintenance_due", "Maintenance Due"),
                            ("maintenance_overdue", "Maintenance Overdue"),
                            ("warranty_expiring", "Warranty Expiring"),
                            ("warranty_expired", "Warranty Expired"),
                            ("downtime_exceeded", "Downtime Exceeded"),
                            ("license_expiration", "License Expiration"),
                            ("license_seat_exhaustion", "License Seat Exhaustion"),
                            ("compliance_violation", "Compliance Violation"),
                            ("vendor_sla_violation", "Vendor SLA Violation"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("message", models.TextField(blank=True, default="")),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_alerts",
                        to="scanner_api.asset",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="maintenance.softwarelicense",
                    ),
                ),
                (
                    "maintenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="maintenance.maintenancerecord",
                    ),
                ),
                (
                    "warranty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="maintenance.warrantyrecord",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("previous_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="maintenance.softwarelicense",
                    ),
                ),
            ],
            options={
                "db_table": "license_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LicenseAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignable_type",
                    models.CharField(
                        choices=[
                            ("Asset", "Asset"),
                            ("Employee", "Employee"),
                            ("Department", "Department"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("removal_date", models.DateField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_assignments",
                        to="scanner_api.asset",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_assignments",
                        to="scanner_api.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_assignments",
                        to="scanner_api.employee",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="maintenance.softwarelicense",
                    ),
                ),
            ],
            options={
                "db_table": "license_assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DowntimeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Maintenance", "Scheduled Maintenance"),
                            ("Repair", "Repair"),
                            ("Failure", "Unexpected Failure"),
                            ("Upgrade", "Upgrade/Update"),
                            ("Power", "Power Outage"),
                            ("Network", "Network Issue"),
                            ("Other", "Other"),
                        ],
                        default="Maintenance",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime_records",
                        to="scanner_api.asset",
                    ),
                ),
                (
                    "maintenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downtime_records",
                        to="maintenance.maintenancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "downtime_records",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("license_expiration", "License Expiration"),
                            ("seat_overuse", "Seat Overuse"),
                            ("unauthorized_software", "Unauthorized Software"),
                            ("missing_license", "Missing License"),
                            ("compliance_violation", "Compliance Violation"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_records",
                        to="scanner_api.asset",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_records",
                        to="maintenance.softwarelicense",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="warrantyrecord",
            index=models.Index(
                fields=["asset", "status"], name="warranty_re_asset_i_6eead4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyrecord",
            index=models.Index(
                fields=["warranty_end"], name="warranty_re_warrant_4a2518_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyrecord",
            index=models.Index(fields=["status"], name="warranty_re_status_00a5a6_idx"),
        ),
        migrations.AddIndex(
            model_name="softwarelicense",
            index=models.Index(
                fields=["software_name"], name="software_li_softwar_d1747c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="softwarelicense",
            index=models.Index(fields=["status"], name="software_li_status_14d64f_idx"),
        ),
        migrations.AddIndex(
            model_name="softwarelicense",
            index=models.Index(
                fields=["expiration_date"], name="software_li_expirat_bceb5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="softwarelicense",
            index=models.Index(
                fields=["-created_at"], name="software_li_created_dca734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["asset", "-created_at"], name="maintenance_asset_i_c1d00d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(fields=["status"], name="maintenance_status_61bdc9_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["maintenance_type"], name="maintenance_mainten_a74f80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["scheduled_date"], name="maintenance_schedul_da449d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["-created_at"], name="maintenance_created_d0399a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancehistory",
            index=models.Index(
                fields=["maintenance", "-timestamp"],
                name="maintenance_mainten_f64f96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancehistory",
            index=models.Index(fields=["action"], name="maintenance_action_e0b04b_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancealert",
            index=models.Index(
                fields=["category", "status"], name="maintenance_categor_4f62ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancealert",
            index=models.Index(
                fields=["severity", "status"], name="maintenance_severit_b6c4fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancealert",
            index=models.Index(
                fields=["-created_at"], name="maintenance_created_072cd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licensehistory",
            index=models.Index(
                fields=["license", "-timestamp"], name="license_his_license_304005_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licensehistory",
            index=models.Index(fields=["action"], name="license_his_action_25c9d5_idx"),
        ),
        migrations.AddIndex(
            model_name="licenseassignment",
            index=models.Index(
                fields=["license", "is_active"], name="license_ass_license_9e7290_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licenseassignment",
            index=models.Index(
                fields=["assignable_type", "is_active"],
                name="license_ass_assigna_103c0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="downtimerecord",
            index=models.Index(
                fields=["asset", "-start_time"], name="downtime_re_asset_i_ba81f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downtimerecord",
            index=models.Index(
                fields=["-start_time"], name="downtime_re_start_t_9ab94c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancerecord",
            index=models.Index(
                fields=["category", "status"], name="compliance__categor_d864ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancerecord",
            index=models.Index(
                fields=["severity", "status"], name="compliance__severit_e65dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancerecord",
            index=models.Index(
                fields=["-created_at"], name="compliance__created_9df111_idx"
            ),
        ),
    ]
