# Generated by Django 4.2.30 on 2026-07-16 06:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scanner_api", "0005_asset_assetvendor_client_device_fingerprint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=32, unique=True)),
                ("release_notes", models.TextField(blank=True, default="")),
                (
                    "download_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                ("min_python_version", models.CharField(default="3.7", max_length=16)),
                ("file_hash", models.CharField(blank=True, default="", max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "monitoring_agent_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceMonitoringInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "monitoring_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("blocked", "Blocked"),
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "health_level",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("health_score", models.IntegerField(default=0, help_text="0-100")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "mac_address",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("public_ip", models.CharField(blank=True, default="", max_length=45)),
                ("os_name", models.CharField(blank=True, default="", max_length=256)),
                ("os_build", models.CharField(blank=True, default="", max_length=128)),
                (
                    "os_architecture",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "agent_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_count", models.IntegerField(default=0)),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("laptop", "Laptop"),
                            ("desktop", "Desktop"),
                            ("server", "Server"),
                            ("workstation", "Workstation"),
                            ("vm", "Virtual Machine"),
                            ("cloud", "Cloud Instance"),
                        ],
                        default="desktop",
                        max_length=32,
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "current_user",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("tags", models.CharField(blank=True, default="", max_length=512)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_info",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_device_info",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("secret_key", models.CharField(max_length=128)),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_secrets",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_agent_secrets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=512)),
                ("version", models.CharField(blank=True, default="", max_length=128)),
                ("publisher", models.CharField(blank=True, default="", max_length=256)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("application", "Application"),
                            ("driver", "Driver"),
                            ("update", "Windows Update"),
                            ("browser", "Browser"),
                            ("office", "Office Suite"),
                            ("antivirus", "Antivirus"),
                            ("service", "Service"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("scan_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "is_present",
                    models.BooleanField(
                        default=True, help_text="False = removed in latest scan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sw_inventories",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_software_inventory",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["client", "category", "-created_at"],
                        name="monitoring__client__da3281_idx",
                    ),
                    models.Index(
                        fields=["client", "name", "-created_at"],
                        name="monitoring__client__fbf798_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HardwareInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU"),
                            ("ram", "RAM"),
                            ("storage", "Storage"),
                            ("gpu", "GPU"),
                            ("motherboard", "Motherboard"),
                            ("network", "Network Adapter"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("component_data", models.JSONField(default=dict)),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of component data for quick diffing",
                        max_length=64,
                    ),
                ),
                ("scan_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hw_inventories",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_hardware_inventory",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "component_type", "-created_at"],
                        name="monitoring__client__e5dbc3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("daily", "Daily")],
                        db_index=True,
                        default="hourly",
                        max_length=8,
                    ),
                ),
                ("avg_cpu_pct", models.FloatField(default=0)),
                ("avg_ram_pct", models.FloatField(default=0)),
                ("avg_disk_pct", models.FloatField(default=0)),
                ("max_cpu_pct", models.FloatField(default=0)),
                ("max_ram_pct", models.FloatField(default=0)),
                ("max_disk_pct", models.FloatField(default=0)),
                ("min_cpu_pct", models.FloatField(default=0)),
                ("min_ram_pct", models.FloatField(default=0)),
                ("min_disk_pct", models.FloatField(default=0)),
                ("health_score", models.IntegerField(default=0)),
                ("health_level", models.CharField(default="unknown", max_length=20)),
                ("uptime_pct", models.FloatField(default=100)),
                ("total_heartbeats", models.IntegerField(default=0)),
                ("missed_heartbeats", models.IntegerField(default=0)),
                ("period_start", models.DateTimeField(db_index=True)),
                ("period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_metrics",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_device_metrics",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["client", "period", "-period_start"],
                        name="monitoring__client__3ae1e5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("registration", "Device Registration"),
                            ("status_change", "Status Change"),
                            ("hardware_change", "Hardware Change"),
                            ("software_change", "Software Change"),
                            ("health_change", "Health Change"),
                            ("security_event", "Security Event"),
                            ("alert_generated", "Alert Generated"),
                            ("admin_action", "Admin Action"),
                            ("agent_update", "Agent Version Update"),
                            ("remote_command", "Remote Command"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("description", models.TextField(default="")),
                ("previous_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(default="system", max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_history",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_device_history",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["client", "-timestamp"],
                        name="monitoring__client__795c2e_idx",
                    ),
                    models.Index(
                        fields=["category", "-timestamp"],
                        name="monitoring__categor_c4f581_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="monitoring__severit_4f6faf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceHeartbeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpu_usage_pct", models.FloatField(default=0)),
                ("ram_usage_pct", models.FloatField(default=0)),
                ("disk_usage_pct", models.FloatField(default=0)),
                ("disk_free_gb", models.FloatField(default=0)),
                ("disk_total_gb", models.FloatField(default=0)),
                ("network_connected", models.BooleanField(default=True)),
                ("uptime_seconds", models.IntegerField(default=0)),
                ("load_average", models.FloatField(default=0)),
                (
                    "agent_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("scan_running", models.BooleanField(default=False)),
                ("pending_commands", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_heartbeats",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_device_heartbeat",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "-created_at"],
                        name="monitoring__client__e0669d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alert_type", models.CharField(db_index=True, max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("message", models.TextField(default="")),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_alerts",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_device_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "status", "-created_at"],
                        name="monitoring__client__4b6b72_idx",
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="monitoring__severit_26ebdf_idx",
                    ),
                ],
            },
        ),
    ]
