# Generated by Django 4.2.30 on 2026-07-18 02:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("scanner_api", "0005_asset_assetvendor_client_device_fingerprint_and_more"),
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("interval", "Interval"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("once", "One-Time"),
                        ],
                        default="interval",
                        max_length=16,
                    ),
                ),
                (
                    "interval_seconds",
                    models.IntegerField(
                        default=3600,
                        help_text="For interval type: seconds between runs",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For cron-type schedules",
                        max_length=128,
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        blank=True,
                        help_text="For daily/weekly/monthly: time to run",
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True, help_text="0=Mon..6=Sun for weekly", null=True
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, help_text="1-31 for monthly", null=True
                    ),
                ),
                (
                    "target_all",
                    models.BooleanField(default=True, help_text="Apply to all clients"),
                ),
                (
                    "target_platforms",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated: Windows,Linux,Darwin",
                        max_length=256,
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Scan"),
                            ("quick", "Quick Scan"),
                            ("hardware", "Hardware Only"),
                            ("software", "Software Only"),
                        ],
                        default="full",
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_clients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scheduled_scans",
                        to="scanner_api.client",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_scheduled_scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanScheduleLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("triggered", "Triggered"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (offline)"),
                        ],
                        default="triggered",
                        max_length=16,
                    ),
                ),
                ("changes_detected", models.IntegerField(default=0)),
                ("alerts_generated", models.IntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_schedule_logs",
                        to="scanner_api.client",
                    ),
                ),
                (
                    "scheduled_scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring.scheduledscan",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_scan_schedule_logs",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_scan", "-triggered_at"],
                        name="monitoring__schedul_3d3b14_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PendingScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scan_type", models.CharField(default="full", max_length=32)),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="Higher = more urgent"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent to Agent"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_scans",
                        to="scanner_api.client",
                    ),
                ),
                (
                    "scheduled_scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring.scheduledscan",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_pending_scans",
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "status"],
                        name="monitoring__client__90c7c9_idx",
                    )
                ],
            },
        ),
    ]
